// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:sehatkita/firebase_options.dart'
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAneB1U9i2PpJUPcX3RRBI5kTQmtSY9n30',
    appId: '1:913055739503:web:9ffba0d145997c12dee79a',
    messagingSenderId: '913055739503',
    projectId: 'sehatkita-6c0ff',
    authDomain: 'sehatkita-6c0ff.firebaseapp.com',
    storageBucket: 'sehatkita-6c0ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQf061UVWU_GGS-ZjAuhhJ5dFPgS1ZCo8',
    appId: '1:913055739503:android:c1f7bc38429b0030dee79a',
    messagingSenderId: '913055739503',
    projectId: 'sehatkita-6c0ff',
    storageBucket: 'sehatkita-6c0ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhN1Pu6KOwR7frNhHBoD1PnvM4KhWFCqc',
    appId: '1:913055739503:ios:63dc4e84344c636bdee79a',
    messagingSenderId: '913055739503',
    projectId: 'sehatkita-6c0ff',
    storageBucket: 'sehatkita-6c0ff.firebasestorage.app',
    iosBundleId: 'com.example.sehatkita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhN1Pu6KOwR7frNhHBoD1PnvM4KhWFCqc',
    appId: '1:913055739503:ios:63dc4e84344c636bdee79a',
    messagingSenderId: '913055739503',
    projectId: 'sehatkita-6c0ff',
    storageBucket: 'sehatkita-6c0ff.firebasestorage.app',
    iosBundleId: 'com.example.sehatkita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAneB1U9i2PpJUPcX3RRBI5kTQmtSY9n30',
    appId: '1:913055739503:web:de74ad2cea7bc6d3dee79a',
    messagingSenderId: '913055739503',
    projectId: 'sehatkita-6c0ff',
    authDomain: 'sehatkita-6c0ff.firebaseapp.com',
    storageBucket: 'sehatkita-6c0ff.firebasestorage.app',
  );
}
