name: sehatkita
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1

# SDK Environment
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  firebase_auth: ^4.3.0
  firebase_auth_web: ^5.8.13  # Ensure this is the correct version for web support
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.4.0  # Firebase storage for file storage
  flutter_native_splash: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Flutter linting recommendations for better practices

flutter:
  uses-material-design: true
  
flutter_native_splash:
  color: "#42a5f5"  # Ganti dengan warna yang diinginkan
  image: assets/splash_logo.png  # Gambar logo splash screen
  android: true
  ios: true


  # If you have images or other assets, uncomment and add the paths
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # If you need custom fonts, uncomment the fonts section
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
